### ISSUE TITLE
Need to adjust font sizes throughout

### ISSUE THREAD

**Issue by mienkoja** [mienkoja/SSWR_R_Workshop_2015#1]

**Comment by smithrichardj** [comment]
I used slidy because it has a simple global command (available in knitr options dialogue box). It's called font_adjustment: n where n is a real number indicated the font size change. I used 4. I think this also adjusts the font in the beamer PDF of the slides. The ioslides function has two font sizes with larger as the default. Both may be changed using a .css file, but I can't be bothered to create one at this time. I had to trim down the language of some slides to get them to fit.

**Comment by mienkoja** [comment]
reopening this issue as it didn't make it into the master repo

**Comment by smithrichardj** [comment]
Rather than do an .html slidy font_adjustment, I think it makes sense to use the "b" for bigger or "s" for smaller keys during a live presentations to make the font bigger/smaller. This can be done with other browser shortcuts if done in a browser. The problem with font_adjustment is that it ends up making the graphics too small relative to text.
